### ISSUE TITLE
Trying to compile

### ISSUE THREAD

**Issue by ithinkido** [usaatyuk/EggbotWireless#2]
Hi,
I am not able to compile the firmware in PIO, looks like I am probably missing something. Would it be possible for you to give a short instruction in the readme on what is needed for this.
Many Thanks

**Comment by usaatyuk** [comment]
Hi, and thank you for interest in this thing!
Are you trying to do this on windows?
If yes, then you need to clone this repo with symlinks, like this `git clone -c core.symlinks=true <URL>`
Look here for more info https://stackoverflow.com/a/42137273

If this doesn't work can you please post the errors you get?

**Comment by ithinkido** [comment]
Thanks, that worked. It compiled and uploaded perfect. I also did 
platformio run --target uploadfs
to uplaod the web page, but I am not sure how to go from there. Is the send box for Gcode input?

**Comment by usaatyuk** [comment]
Yes.
Now creating gcode for this thing is quite tricky - I used the gcodetools Inkscape extension.
The process is something like this:
1. Open Utils/egg.svg with Inkscape
2. Insert something you want to draw as a child of Layer 1 (the rectangle is the egg boundary)
3. Make it a path
4. Use path to gcode (Also set minimal arc radius to something big as drawing arcs with g02 is not supported)

Also, did you actually assemble all the hardware?

**Comment by ithinkido** [comment]
So I have a hardware version that i assembled using an UNO + CNC shield. This is working, but i would really like to find a version that can be used wireless like yours. So in short, i have not yet assembled the hardware based on your version, i would like to see how the software works , then change over.
Thanks for the info on the gcode generation. I saw the App section in the code. Is that also used to generate gcode?

**Comment by usaatyuk** [comment]
App/ directory contains the source of the web app. It would be nice if it could generate gcode but it can't do it right now. 😕

**Comment by ithinkido** [comment]
Ok thanks for all the info. Have you seen this 
https://github.com/evomotors/SvgToGCode

**Comment by usaatyuk** [comment]
Actually, I haven’t. Thank you for this link, it looks interesting!)
